### ISSUE TITLE
calls `async_add_job`, which should be reviewed against https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job

### ISSUE THREAD

**Issue by misa1515** [HrGaertner/vent-optimization#23]
Found info in HA log, base on this reported here.
![DeprecatedVentopt](https://github.com/user-attachments/assets/48684b29-4076-4f68-a5e9-f37ce3a5a163)

![DeprecatedVentOpt2](https://github.com/user-attachments/assets/e56f41cc-b8a1-447c-b606-598369d76a45)

**Comment by HrGaertner** [comment]
Thanks for bringing this to my attention. Did my changes fix it for you? If not simply reopen the issue in the HA repository
